### ISSUE TITLE
System.AccessViolationException / Crash / Memory Leak

### ISSUE THREAD

**Issue by Meisterlala** [Meisterlala/NekoLife#1]
When i try to load an Image async/threaded with DalamudPluginInterface.UiBuilder.LoadImageAsync(byte[] data)
I sometimes (once every 50 calls or so) get a System.AccessViolationException from SharpDX.Direct3D11.Device.CreateTexture2D(...)

I think it is a problem with the Garbage collector freeing the data while the image is still being loaded to the GPU. I tried pausing the Garbage collector while the image is still being loaded, which worked. But this causes a huge memory leek. With no changes to the Garbage collector the memory usage also keeps increasing until it is collected automaticly, which causes the System.AccessViolationException.

I can also call DalamudPluginInterface.UiBuilder.LoadImage(byte[] data) on the main thread, which doesn't produce the bug but freezes the game while a new image is loading.

Here is some code to repruduce the bug:
```csharp
public async static void LoadLoop()
{
    TextureWrap? img;
    // 16MB   9600x5400
    byte[] data = System.IO.File.ReadAllBytes("C:\\Temp\\big_image.png");

    for (int i = 0; i < 100; i++)
    {
        try
        {
            // System.GC.TryStartNoGCRegion(data.Length * 2);
            img = await Plugin.PluginInterface.UiBuilder.LoadImageAsync(data);
            PluginLog.Log("Loaded image at: " + img.ImGuiHandle + " in Thread:" + Thread.CurrentThread.ManagedThreadId);
        }
        catch (System.Exception ex)
        {
            PluginLog.LogError(ex, "System.AccessViolationException catched");
        }
        
        // try { System.GC.EndNoGCRegion(); }
        // catch (System.Exception) { PluginLog.LogError("Could not end GC region"); }

        // System.GC.Collect();
    }
}
```` 

Stack trace of Bug
```csharp
2022-07-31 21:13:59.498 +02:00 [ERR] Failed to load image from memory
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description, DataRectangle[] data)
   at ImGuiScene.RawDX11Scene.CreateTexture(Void* pixelData, Int32 width, Int32 height, Int32 bytesPerPixel) in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 257
   at ImGuiScene.RawDX11Scene.LoadImage_Internal(StbiImage image) in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 221
   at ImGuiScene.RawDX11Scene.LoadImage(Byte[] imageBytes) in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 202
   at Dalamud.Interface.Internal.InterfaceManager.LoadImage(Byte[] imageData) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 263
```

**Comment by Meisterlala** [comment]
If anyone is a C# wizard or knows DX11 and has any idea on how to fix this, please message me.

**Comment by Meisterlala** [comment]
"Fixed" for now by stopping the GC before calling `PluginInterface.UiBuilder.LoadImageAsync(data)` and resuming afterwards. It still causes a `System.AccessViolationException` sometimes. The inner workings of the C# GarbageCollector are beyond me.

Commit 0058395db8c7f03598c7b255237030d696c9f1b1

**Comment by Meisterlala** [comment]
I fixed it by just not calling ```Plugin.PluginInterface.UiBuilder.LoadImageAsync(data);``` any more and instead decoding image data and loading it to the GPU by myself.
